const Cmp = [
    {
        id :'masala',
        image: "../img/chilli.jpg",
        title : "Chilli Powder",
        category:"Masala",
        description : "Good Quality Chilli Powder with no added artificial colors, Available in Packet-Pouch, Available in different weights.",
    },
    {
        image: "../img/garam.jpg",
        title : "Garam Masala",
        category:"Masala",
        description : "Good Quality Garam Masala with no added artificial colors, Available in Packet-Pouch, Available in different weights.",
    },
    {
        image: "../img/turmeric.jpg",
        title : "Turmeric Powder",
        category:"Masala",
        description : "Good Quality turmeric Powder with no added artificial colors, Available in Packet-Pouch, Available in different weights.",
    },
    {
        image: "../img/cumin.jpg",
        title : "Cumin Powder",
        category:"Masala",
        description : "Good Quality Cumin Powder with no added artificial colors, Available in Packet-Pouch, Available in different weights.",
    },
    {
        image: "../img/coriander.jpg",
        title : "Coriander Powder",
        category:"Masala",
        description : "Good Quality Coriander Powder with no added artificial colors, Available in Packet-Pouch, Available in different weights.",
    },
    {
        id :"peanut",
        image: "../img/salted.jpg",
        title : "Classic Salted Peanuts",
        category:"Peanuts",
        description : "Good Quality Salted Peanut, Available in Packet-Pouch, Available in different weights.",
    },
    {
        image: "../img/salted.jpg",
        title : "Roasted Peanut",
        category:"Peanuts",
        description : "Good Quality Roasted Peanut , Available in Packet-Pouch, Available in different weights. Sub-products: Hing Jeera, Nimboo Pudina, Black pepper, Masala Mix.",
    },
    {
        image: "../img/rchana.jpg",
        title : "Roasted Chana",
        category:"Peanuts",
        description : "Good Quality Roasted Chana , Available in Packet-Pouch, Available in different weights. Sub-Products: Classic Salted, Hing jeera, Nimboo Pudina, Black pepper, Tangy Tomato, Peri Peri, Tandoori Barbeque.",
    },
    {
        image: "../img/chana.jpg",
        title : "Classic Salted Chana  with turmeric",
        category:"Peanuts",
        description : "Good Quality Slated Chana with turmeric, Available in Packet-Pouch, Available in different weights.",
    },
    {
        id :'flour',
        image: "../img/wheat.jpg",
        title : "Wheat Flour",
        category:"Flours",
        description : "Good Quality Wheat Flour, Available in Packet-Pouch, Available in different weights.",
    },
    {
        image: "../img/maida.jpg",
        title : "Maida",
        category:"Flours",
        description : "Good Quality Maida, Available in Packet-Pouch, Available in different weights.",
    },
    {
        image: "../img/bajra.jpg",
        title : "Bajra Flour",
        category:"Flours",
        description : "Good Quality Bajra Flour, Available in Packet-Pouch, Available in different weights.",
    },
    {
        image: "../img/corn.jpg",
        title : "Maize Flour",
        category:"Flours",
        description : "Good Quality Maize Flour, Available in Packet-Pouch, Available in different weights.",
    },
    {
        image: "../img/multigrain.jpg",
        title : "Multigrain Flour",
        category:"Flours",
        description : "Good Quality Multigrain Flour, Available in Packet-Pouch, Available in different weights.",
    },
    {
        id :'cattle-feed',
        image: "../img/maize.jpg",
        title : "Maize Broken",
        category:"Cattle Feed",
        description : "Good Quality Maize Broken, Available in Packet-Pouch, Available in different weights. Size:3-4mm or 2.5-3mm.",
    },
    {
        image: "../img/corngrit.jpg",
        title : "Corn Grits",
        category:"Cattle Feed",
        description : "Good Quality Corn grits, Available in Packet-Pouch, Available in different weights. Size: <0.8mm",
    },
    {
        image: "../img/cornfibre.jpg",
        title : "Corn Fibre",
        category:"Cattle Feed",
        description : "Good Quality Corn Fibre, Available in Packet-Pouch, Available in different weights.",
    },
    {
        image: "../img/maida.jpg",
        title : "Maize Powder",
        category:"Cattle Feed",
        description : "Good Quality Maize powder, Available in Packet-Pouch, Available in different weights.",
    },
    {
        image: "../img/soyabean.jpeg",
        title : "Soyabean Crunch",
        category:"Cattle Feed",
        description : "Soyabean Crunch is by-products obtained after oil extraction from soyabeans. It contains 45%-48% protein and considered as good cattle-feed.",
    },
    {
        id :'cereal',
        image: "../img/maize.jpg",
        title : "Maize Germs",
        category:"Cereals",
        description : "Maize Germs is mainly used for maize oil and manufacturinf feed supplements, Available in Packet-Pouch, Available in different weights.",
    },
    {
        image: "../img/rice.jpg",
        title : "Rice",
        category:"Cereals",
        description : "Good Quality Rice, Long-term prepared, Available in Packet-Pouch, Available in different weights.",
    },
    {
        image: "../img/dal.png",
        title : "Toor Dal",
        category:"Cereals",
        description : "Good Quality Toor Dal, Available in Packet-Pouch, Available in different weights.",
    },
    {
        image: "../img/soybean.jpg",
        title : "Soybean",
        category:"Cereals",
        description : "Good Quality Soybean, Available in Packet-Pouch, Available in different weights.",
    },
    {
        id :'raw',
        image: "../img/raw.jpg",
        title : "Ready Mix Plaster",
        category:"Construction and Raw Material",
        description : "Ready-mix plaster, Sand and Plasters, Quartz Sand, Gravels/Payable, Available in Packet-Pouch, Available in different weights.",
    },

]
export default Cmp;